#!/bin/bash

file=$HOME/pythontestscripts/nameandagelist
age=$(cat $file | awk {'print $2'})

while read $age
	if (($(age) >= 18))
	then echo $age
	fi
#while read -r line
#do
#	if (( $age -gt 18 )); then
#		echo "$age"
#	fi
#done
