--- # This playbook demo of debug and register statement
- hosts: ubuntu-node-01
  remote_user: ansible
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: no
  tasks:
   - name: Installing telnet package
     apt:
       name: telnet
       state: latest
     register: result
   - debug: var=result
