--- # Notification and Handling events
- hosts: all
  remote_user: ansible
  become: yes
  become_method: sudo
  gather_facts: no
  connection: ssh
  tasks:
  - name: Install and run 'screenfetch'
    apt:
      name: screenfetch
      state: latest

  - name: run 'screenfetch'
    command: /usr/bin/screenfetch -n -N
    register: out
  
  - debug: var=out.stdout_lines
    
