--- # Equivalent of running apt update; apt upgrade
- hosts: all
  remote_user: ansible
  become: yes
  become_method: sudo
  gather_facts: no
  connection: ssh
  
  tasks:
  - name: Run "update_cache=yes" if the last one is more than 3600 seconds ago
    apt:
      update_cache: yes
      cache_valid_time: 3600 #one hour, in seconds
    register: aptupdate
  - debug: var=aptupdate.stdout_lines
    
  - name: Upgrade installed packages
    apt:
      upgrade: dist
      state: latest
    register: aptupgrade
  - debug: var=aptupgrade.stdout_lines
