--- #Testing how variables in the vars section of a playbook
- hosts: '{{ myhost }}'
  remote_user: ansible
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: '{{ gather }}'
  vars:
          myhost: ubuntu-node-01
          gather: yes
          pkg: telnet
  tasks:
  - name: Install indicated software
    apt:
      name: '{{ pkg }}'
      state: latest
